// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var empty_categories = [];

var empty = {
  dateRange: undefined,
  categories: empty_categories,
  minValue: undefined,
  maxValue: undefined,
  sortBy: "date",
  sortDirection: "desc"
};

function toJson(filters) {
  var json = {};
  var match = filters.dateRange;
  if (match !== undefined) {
    json["startDate"] = match[0].toISOString();
    json["endDate"] = match[1].toISOString();
  }
  if (filters.categories.length !== 0) {
    json["categories"] = (function (__x) {
          return Belt_Array.map(__x, (function (c) {
                        return c;
                      }));
        })(filters.categories);
  }
  var value = filters.minValue;
  if (value !== undefined) {
    json["minValue"] = value;
  }
  var value$1 = filters.maxValue;
  if (value$1 !== undefined) {
    json["maxValue"] = value$1;
  }
  json["sortBy"] = filters.sortBy;
  json["sortDirection"] = filters.sortDirection;
  return json;
}

function fromJson(json) {
  var dict = Belt_Option.getWithDefault(Js_json.decodeObject(json), {});
  var startDateJson = Js_dict.get(dict, "startDate");
  var endDateJson = Js_dict.get(dict, "endDate");
  var dateRange;
  if (startDateJson !== undefined && endDateJson !== undefined) {
    var startDateStr = Belt_Option.getWithDefault(Js_json.decodeString(startDateJson), "");
    var endDateStr = Belt_Option.getWithDefault(Js_json.decodeString(endDateJson), "");
    dateRange = startDateStr !== "" && endDateStr !== "" ? [
        new Date(startDateStr),
        new Date(endDateStr)
      ] : undefined;
  } else {
    dateRange = undefined;
  }
  var categoriesJson = Js_dict.get(dict, "categories");
  var categories = categoriesJson !== undefined ? Belt_Array.keep(Belt_Array.map(Belt_Option.getWithDefault(Js_json.decodeArray(categoriesJson), []), (function (item) {
                return Belt_Option.getWithDefault(Js_json.decodeString(item), "");
              })), (function (s) {
            return s !== "";
          })) : [];
  var minValueJson = Js_dict.get(dict, "minValue");
  var minValue = minValueJson !== undefined ? Js_json.decodeNumber(minValueJson) : undefined;
  var maxValueJson = Js_dict.get(dict, "maxValue");
  var maxValue = maxValueJson !== undefined ? Js_json.decodeNumber(maxValueJson) : undefined;
  var sortByJson = Js_dict.get(dict, "sortBy");
  var sortBy = sortByJson !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(sortByJson), "date") : "date";
  var sortDirectionJson = Js_dict.get(dict, "sortDirection");
  var sortDirection = sortDirectionJson !== undefined ? Belt_Option.getWithDefault(Js_json.decodeString(sortDirectionJson), "desc") : "desc";
  return {
          dateRange: dateRange,
          categories: categories,
          minValue: minValue,
          maxValue: maxValue,
          sortBy: sortBy,
          sortDirection: sortDirection
        };
}

export {
  empty ,
  toJson ,
  fromJson ,
}
/* No side effect */
